# Generated by Django 4.1.6 on 2024-04-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("category", models.PositiveIntegerField(verbose_name="Cathegory")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                ("count", models.PositiveIntegerField(verbose_name="Count")),
                ("date", models.DateTimeField(verbose_name="Date")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "fullDescription",
                    models.TextField(
                        blank=True, null=True, verbose_name="FullDescription"
                    ),
                ),
                (
                    "freeDelivery",
                    models.BooleanField(default=False, verbose_name="FreeDelivery"),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=3,
                        verbose_name="Rating",
                    ),
                ),
            ],
        ),
    ]
