# Generated by Django 4.1.6 on 2024-04-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0002_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "tag_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Tag_ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=50, verbose_name="Name"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="shopapp.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
    ]
