# Generated by Django 4.1.6 on 2024-04-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0005_specification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="alt",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="src",
            field=models.ImageField(
                blank=True,
                default="default.png",
                null=True,
                upload_to="product_image/",
                verbose_name="Link",
            ),
        ),
    ]
