# Generated by Django 4.1.6 on 2024-05-02 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0009_imagecategory_subcategory_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="shopapp.category",
                verbose_name="Category",
            ),
        ),
    ]
