# Generated by Django 4.1.6 on 2024-05-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0011_product_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="product",
        ),
        migrations.AddField(
            model_name="tag",
            name="product",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="shopapp.product"
            ),
        ),
    ]
