# Generated by Django 4.1.6 on 2024-05-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0012_remove_tag_product_tag_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "salePrice",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Sale Price"
                    ),
                ),
                ("dateFrom", models.DateField(verbose_name="Sale Start Date")),
                ("dateTo", models.DateField(verbose_name="Sale End Date")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="shopapp.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "product_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopapp.image",
                        verbose_name="Product Image",
                    ),
                ),
            ],
        ),
    ]
