# Generated by Django 4.1.6 on 2024-05-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0015_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="limited_edition",
            field=models.BooleanField(default=False),
        ),
    ]
