# Generated by Django 4.1.6 on 2024-05-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0016_product_limited_edition"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sales_count",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="sort_index",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
