# Generated by Django 4.1.6 on 2024-05-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0017_product_sales_count_product_sort_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=0.0,
                max_digits=3,
                null=True,
                verbose_name="Rating",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sales_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sort_index",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
