# Generated by Django 4.1.6 on 2024-05-29 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("myauth", "0005_alter_avatar_src"),
        ("shopapp", "0019_remove_specification_product_specification_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "deliveryType",
                    models.CharField(
                        choices=[
                            ("ordinary", "Free Delivery"),
                            ("express", "Express Delivery"),
                        ],
                        default="ordinary",
                        max_length=50,
                        verbose_name="Delivery Type",
                    ),
                ),
                (
                    "paymentType",
                    models.CharField(
                        choices=[
                            ("online", "Online Card"),
                            ("someone", "Online Account"),
                        ],
                        max_length=100,
                        verbose_name="Payment Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("accepted", "Accepted"), ("pending", "Pending")],
                        default="pending",
                        max_length=100,
                        verbose_name="Status",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "address",
                    models.TextField(
                        blank=True, max_length=255, null=True, verbose_name="Address"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "delivery_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "totalCost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="myauth.profile",
                        verbose_name="Profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=16, verbose_name="Card Number")),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Name of card owner"),
                ),
                (
                    "month",
                    models.CharField(
                        max_length=2, verbose_name="Month until card is valid"
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        max_length=4, verbose_name="Year until card is valid"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3, verbose_name="Secret verification code"
                    ),
                ),
                (
                    "order_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="orderapp.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Price"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantity product in order"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products_in_order",
                        to="orderapp.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopapp.product",
                        verbose_name="Product",
                    ),
                ),
            ],
        ),
    ]
