# Generated by Django 4.1.6 on 2024-05-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="totalCost",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
