# Generated by Django 4.1.6 on 2024-06-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0002_alter_order_totalcost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="updated",
        ),
        migrations.AlterField(
            model_name="order",
            name="deliveryType",
            field=models.CharField(
                choices=[
                    ("ordinary", "Free_Delivery"),
                    ("express", "Express_Delivery"),
                ],
                default="ordinary",
                max_length=10,
                verbose_name="Delivery Type",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="paymentType",
            field=models.CharField(
                choices=[("online", "Online Card"), ("someone", "Online Account")],
                default="online",
                max_length=10,
                verbose_name="Payment Type",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("accepted", "Accepted")],
                default="pending",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="totalCost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
