# Generated by Django 4.1.6 on 2024-06-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0003_remove_order_updated_alter_order_deliverytype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="order_item_images/",
                verbose_name="Image",
            ),
        ),
    ]
