# Generated by Django 4.1.6 on 2024-06-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0004_orderitem_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-createdAt",),
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Order Item",
                "verbose_name_plural": "Order Items",
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Payment", "verbose_name_plural": "Payments"},
        ),
        migrations.RemoveField(
            model_name="order",
            name="created",
        ),
        migrations.AlterField(
            model_name="order",
            name="deliveryType",
            field=models.CharField(
                choices=[
                    ("ordinary", "Free Delivery"),
                    ("express", "Express Delivery"),
                ],
                default="ordinary",
                max_length=10,
                verbose_name="Delivery Type",
            ),
        ),
    ]
