# Generated by Django 4.1.6 on 2024-06-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0006_alter_order_deliverytype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="delivery_cost",
            new_name="deliveryCost",
        ),
        migrations.AlterField(
            model_name="order",
            name="deliveryType",
            field=models.CharField(
                choices=[
                    ("ordinary", "Free Delivery"),
                    ("express", "Express Delivery"),
                ],
                default="ordinary",
                max_length=10,
                verbose_name="Delivery Type",
            ),
        ),
    ]
