# Generated by Django 4.1.6 on 2024-06-19 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0007_rename_delivery_cost_order_deliverycost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="deliveryCost",
        ),
    ]
