# Generated by Django 4.1.6 on 2024-06-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0008_remove_order_deliverycost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="quantity",
            new_name="count",
        ),
    ]
