# Generated by Django 4.1.6 on 2024-06-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0010_alter_order_city_alter_order_deliverytype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("accepted", "Accepted")],
                default="pending",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
