# Generated by Django 4.1.6 on 2024-07-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0011_alter_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="order_id",
            new_name="order",
        ),
    ]
