# Generated by Django 4.1.6 on 2024-07-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0012_rename_order_id_payment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
