# Generated by Django 4.1.6 on 2024-07-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0014_payment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="number",
            field=models.CharField(max_length=8, verbose_name="Card Number"),
        ),
    ]
