# Generated by Django 4.1.6 on 2024-07-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0015_alter_payment_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
