# Generated by Django 4.1.6 on 2024-07-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderapp", "0017_alter_payment_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("confirmed", "Confirmed"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
