# Generated by Django 4.1.6 on 2024-04-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0002_alter_profile_avatar_alter_profile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="alt",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Description"
            ),
        ),
    ]
