# Generated by Django 4.1.6 on 2024-04-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0004_alter_avatar_alt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatar",
            name="src",
            field=models.ImageField(
                blank=True,
                default="app_users/avatars/default.png",
                null=True,
                upload_to="app_users/avatars/user_avatars/",
                verbose_name="Link",
            ),
        ),
    ]
